ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - '@reown/appkit'
