import type { Metadata } from 'next'
import { Lobster, Open_Sans } from 'next/font/google'
import './styles/globals.scss'
import { GlobalLayout } from '@/layouts/global-layout'

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-open-sans',
})

const lobster = Lobster({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-lobster',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${lobster.variable} antialiased`}>
        <GlobalLayout>{children}</GlobalLayout>
      </body>
    </html>
  )
}
